"""Generate plain-text analytics reports from the Kleos database.

Reports are designed for clipboard sharing — human-readable, plain-text
summaries suitable for pasting into Discord, forums, or community channels.
"""
from __future__ import annotations

from datetime import datetime, timezone, timedelta
from typing import Any

from core.db_manager import DatabaseManager
from ui.components.creator_card import _compact_number


def generate_report(db: DatabaseManager, period: str = 'monthly', role_id: int | None = None, verified_only: bool = True) -> str:
    """Generate a human-readable plain-text analytics report.

    Args:
        db: DatabaseManager instance for the active profile.
        period: 'weekly', 'monthly', or 'yearly' — controls the date range.
        role_id: Optional role filter — only include creators with this role.
        verified_only: When True (default), only count verified content.

    Returns:
        A multi-line plain-text string suitable for clipboard sharing.
    """
    now = datetime.now(timezone.utc)
    if period == 'weekly':
        since = now - timedelta(weeks=1)
        period_label = 'Weekly'
    elif period == 'yearly':
        since = now - timedelta(days=365)
        period_label = 'Yearly'
    else:  # monthly
        since = now - timedelta(days=30)
        period_label = 'Monthly'

    since_str = since.strftime('%Y-%m-%dT%H:%M:%SZ')

    # Filter creators by role if requested
    creators = db.get_creators()
    if role_id is not None:
        creators = [c for c in creators if c.get('role_id') == role_id]

    roles = {r['id']: r for r in db.get_roles()}
    sub_counts = db.bulk_subscriber_counts()

    lines: list[str] = []
    lines.append('=== Kleos Analytics Report ===')
    lines.append(f'Period: {since.strftime("%b %d, %Y")} - {now.strftime("%b %d, %Y")}')

    # Per-creator stats within the period
    total_views = 0
    total_uploads = 0
    creator_stats: list[dict[str, Any]] = []

    verified_clause = 'AND is_verified = 1' if verified_only else ''
    for c in creators:
        cid = c['id']
        date_clause = f"AND upload_date >= '{since_str}'" if since_str else ''
        rows = db._read(
            f"SELECT COALESCE(SUM(view_count), 0) AS views, COUNT(*) AS count "
            f"FROM media_content WHERE creator_id = ? {verified_clause} {date_clause}",
            (cid,),
        )
        views = rows[0]['views'] if rows else 0
        count = rows[0]['count'] if rows else 0
        total_views += views
        total_uploads += count

        counts = sub_counts.get(cid, {})
        sub_parts = []
        if counts.get('youtube', 0):
            sub_parts.append(f'{_compact_number(counts["youtube"])} subs')
        if counts.get('twitch', 0):
            sub_parts.append(f'{_compact_number(counts["twitch"])} flw')

        creator_stats.append({
            'nickname': c['nickname'],
            'views': views,
            'uploads': count,
            'sub_text': ' | '.join(sub_parts) if sub_parts else 'N/A',
        })

    lines.append(f'Total Uploads (period): {total_uploads:,}')
    lines.append(f'Total Views (period): {total_views:,}')
    lines.append('')

    # Leaderboard sorted by views
    lines.append('--- Leaderboard ---')
    creator_stats.sort(key=lambda s: s['views'], reverse=True)
    for i, cs in enumerate(creator_stats, 1):
        lines.append(
            f'{i}. {cs["nickname"]} — {cs["views"]:,} views, '
            f'{cs["uploads"]} uploads | {cs["sub_text"]}'
        )

    lines.append('')
    lines.append(f'Generated by Kleos on {now.strftime("%Y-%m-%d %H:%M UTC")}')
    return '\n'.join(lines)